name: cabby
description: Cabby taxi app
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.11+2

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.2.0
  shared_preferences: ^2.2.2
  cookie_jar: ^4.0.8
  dio: ^5.3.3
  dio_cookie_manager: ^3.1.1
  intl: 0.18.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  cached_network_image: ^3.3.0
  flutter_datetime_picker: ^1.5.1
  path_provider: ^2.1.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.14
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.6.0
  country_code_picker: ^3.0.0
  file_picker: ^6.0.0
  flutter_speed_dial: ^7.0.0
  pin_code_fields: ^8.0.1
  numeric_keyboard: ^1.1.0
  jwt_decoder: ^2.0.1
  im_stepper: ^1.0.1+1
  signature: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  go_router: ^13.0.1
  fluttertoast: ^8.2.2
  flutter_pdfview: ^1.3.2
  flutter_spinkit: ^5.2.0
  camera: ^0.10.5+5
  image: ^4.1.3
  pdf: ^3.10.4
  pdf_image_renderer: ^0.7.0
  photo_view: ^0.14.0
  uni_links: ^0.5.1
  webview_flutter: ^4.4.1
  shimmer: ^3.0.0
  flutter_cache_manager: ^3.3.1
  supabase: ^2.0.3
  supabase_flutter: ^2.1.0
  uuid: ^4.1.0
  logger: ^2.0.2+1
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  flutter_local_notifications: ^16.2.0
  package_info_plus: ^5.0.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/images/logo.png
    - .env

  fonts:
    - family: THICCCBOI
      fonts:
        - asset: assets/fonts/thicccboi/TTF/THICCCBOI-Black.ttf
        - asset: assets/fonts/thicccboi/TTF/THICCCBOI-ExtraBold.ttf
        - asset: assets/fonts/thicccboi/TTF/THICCCBOI-Medium.ttf
        - asset: assets/fonts/thicccboi/TTF/THICCCBOI-SemiBold.ttf
        - asset: assets/fonts/thicccboi/TTF/THICCCBOI-Thin.ttf
        - asset: assets/fonts/thicccboi/TTF/THICCCBOI-Bold.ttf
        - asset: assets/fonts/thicccboi/TTF/THICCCBOI-Light.ttf
        - asset: assets/fonts/thicccboi/TTF/THICCCBOI-Regular.ttf
        - asset: assets/fonts/thicccboi/TTF/THICCCBOI-ThicccAF.ttf
