// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvOE7esOEkBW_2AUTsMeng4RkBMDAAwUQ',
    appId: '1:46803388955:web:02768aa00d80d1c15106be',
    messagingSenderId: '46803388955',
    projectId: 'cabby-60c8c',
    authDomain: 'cabby-60c8c.firebaseapp.com',
    storageBucket: 'cabby-60c8c.appspot.com',
    measurementId: 'G-5CNMNVYFBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNtQYHAUYp5nOXrafqNY593nlMWFva1lY',
    appId: '1:46803388955:android:910b7e51824595765106be',
    messagingSenderId: '46803388955',
    projectId: 'cabby-60c8c',
    storageBucket: 'cabby-60c8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBuFsFAyBt3l40YtAMMYJHCv74F2UdMo8',
    appId: '1:46803388955:ios:83576b06ac72a0ac5106be',
    messagingSenderId: '46803388955',
    projectId: 'cabby-60c8c',
    storageBucket: 'cabby-60c8c.appspot.com',
    iosBundleId: 'com.example.cabby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBuFsFAyBt3l40YtAMMYJHCv74F2UdMo8',
    appId: '1:46803388955:ios:c018c78e5709e38e5106be',
    messagingSenderId: '46803388955',
    projectId: 'cabby-60c8c',
    storageBucket: 'cabby-60c8c.appspot.com',
    iosBundleId: 'com.example.cabby.RunnerTests',
  );
}
